name: Search results format change
description: Report that the workflow can't read Letterboxd's search results
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Workflow version
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Search type
      options:
        - films
        - people
    validations:
      required: true
  - type: input
    id: query
    attributes:
      label: Search query
      description: What did you type? (optional)
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
